name: Build and Sign Android App

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Secrets
        run: |
          errors=0
          if [ -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo "::error::Secret 'SIGNING_KEY' is empty or missing! Please add it in GitHub Settings -> Secrets and variables -> Actions."
            errors=$((errors+1))
          fi
          if [ -z "${{ secrets.ALIAS }}" ]; then
            echo "::error::Secret 'ALIAS' is empty or missing! Please add it in GitHub Settings -> Secrets and variables -> Actions."
            errors=$((errors+1))
          fi
          if [ -z "${{ secrets.KEY_STORE_PASSWORD }}" ]; then
            echo "::error::Secret 'KEY_STORE_PASSWORD' is empty or missing! Please add it in GitHub Settings -> Secrets and variables -> Actions."
            errors=$((errors+1))
          fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "::error::Secret 'KEY_PASSWORD' is empty or missing! Please add it in GitHub Settings -> Secrets and variables -> Actions."
            errors=$((errors+1))
          fi
          if [ $errors -ne 0 ]; then
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create fallback .env file
        run: touch .env

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper
          chmod +x gradlew

      - name: Build Unsigned Release APK
        run: ./gradlew :app:assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
